name: Java Docker CI-CD

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------- JAVA BUILD ----------------

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build JAR
        run: ./mvnw.cmd clean package -DskipTests

      # ---------------- DOCKER BUILD ----------------
      - name: Login to Docker Hub
        shell: powershell
        run: |
          $pass="${{ secrets.DOCKERHUB_TOKEN }}"
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password $pass
      

#      - name: Login to Docker Hub
#        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin


  # Build image
      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-k8s:${{ github.run_number }} .

  # Push image
      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-k8s:${{ github.run_number }}


      # ---------------- K8S CD ----------------

#      - name: Setup kubectl
#        uses: azure/setup-kubectl@v4

#      - name: Setup Helm
#        uses: azure/setup-helm@v4

#      - name: Configure kubeconfig
#        run: |
#          mkdir -p $HOME/.kube
#          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > $HOME/.kube/config


      - name: Deploy with Helm
        run: helm upgrade --install hello-release ./hello-chart --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/hello-k8s --set image.tag=${{ github.run_number }}

